name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: chetan/git-restore-mtime-action@v2 # Restore modified time from git to files

      - uses: actions/setup-node@v4
        with:
          node-version: 18.14

      - name: Clone quartz (v4 branch)
        run: |
          cd ..
          git clone --depth 1 https://github.com/jackyzha0/quartz.git -b v4

      - name: Copy vault content Quartz
        run: cp -p -R ./* ../quartz/content # Preserve timestamps

      - name: Copy quartz config to the quartz folder
        run: cp quartz.config.ts quartz.layout.ts ../quartz

      - name: Install Dependencies
        run: |
          cd ../quartz
          npm ci
        
      - name: Build Quartz
        run: |
          cd ../quartz
          npx quartz build
        
      - name: Copy favicon to output
        run: cp icon.png ../quartz/public/static/icon.png
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ../quartz/public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
