name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14

      - name: Clone quartz
        run: |
          cd ..
          git clone https://github.com/jackyzha0/quartz.git

      - name: Copy vault content Quartz
        run: cp -R ./* ../quartz/content

      - name: Copy quartz config to the quartz folder
        run: cp quartz.config.ts quartz.layout.ts ../quartz

        
      - name: Install Dependencies
        run: |
          cd ../quartz
          npm ci
        
      - name: Build Quartz
        run: |
          cd ../quartz
          npx quartz build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ../quartz/public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
