name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v3
        with:
          node-version: 18.14
          
      - name: Go to parent directory
        run: cd ..

      - name: Clone quartz
        run: git clone https://github.com/jackyzha0/quartz.git

      - name: Copy vault content Quartz
        run: cp -R $GITHUB_WORKSPACE/* quartz/content

      - name: Copy quartz config to the quartz folder
        run: cp $GITHUB_WORKSPACE/quartz.config.ts $GITHUB_WORKSPACE/quartz.layout.ts quartz
        
      - name: Go into quartz directory
        run: cd quartz
        
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Quartz
        run: npx quartz build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
